### ISSUE TITLE
Have some problem: 'AutoField' object has no attribute 'remote_field'

### ISSUE THREAD

**Issue by DavidDong33** [twtrubiks/django-rest-framework-tutorial#1]
see attach file. Thank u.
![1](https://user-images.githubusercontent.com/16789589/32363808-1d40e886-c0ac-11e7-80b0-51f0bd5ff9d6.png)
![2](https://user-images.githubusercontent.com/16789589/32363814-21829868-c0ac-11e7-9c85-f5f0043619d4.png)

**Comment by twtrubiks** [comment]
django version 1.8.18 , too old , update django version and  try it,
Also, fix your error reminder

**Comment by DavidDong33** [comment]
django version: 1, 11, 7   it's fine.  Thank u.
